version: '3.8'

services:
  couchdb:
    image: couchdb:latest
    volumes:
      - couchdb_data:/opt/couchdb/data
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - "5984:5984"
    networks:
      - star

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
    networks:
      - star

  star-server:
    image: star-server:latest
    environment:
      BUILD_MODE: DEV
      COUCHDB_HOST: couchdb
      RABBITMQ_HOST: rabbitmq
      HTTP_API_LISTEN_ADDRESS: star-server
    ports:
      - "5000:5000"
    networks:
      - star
    depends_on:
      - couchdb
      - rabbitmq

volumes:
  couchdb_data:


networks:
  star:
