version: '3.8'

services:
  couchdb:
    container_name: "couchdb"
    hostname: couchdb
    image: ibmcom/couchdb3
    volumes:
      - couchdb_data:/opt/couchdb/data
    environment:
      #NOTE CHANGE ME
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - "5984:5984"
    networks:
      - star

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    container_name: "rabbitmq"
    environment:
      #NOTE CHANGEME
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - star
  star-server:
    container_name: "star-server"
    restart: always
    image: star-server:latest
    hostname: star-server
    volumes:
      - ./init.lisp:/root/init.lisp
    environment:
      BUILD_MODE: DEV
    ports:
      - "5000:5000"
    networks:
      - star
    depends_on:
      - couchdb
      - rabbitmq



volumes:
  couchdb_data:

networks:
  star:
    name: star
