openapi: 3.0.0
info:
  title: StarIntel HTTP API
  version: 1.0.0
  description: API for managing StarIntel documents and targets
servers:
  - url: http://127.0.0.1:5000
paths:
  /targets/{actor}:
    get:
      summary: Get targets for an actor
      parameters:
        - name: actor
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Target'
  /new/target/{actor}:
    post:
      summary: Create a new target for an actor
      parameters:
        - name: actor
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Target'
      responses:
        '200':
          description: Successful response
  /new/document/{dtype}:
    post:
      summary: Create a new document of a specific type
      parameters:
        - name: dtype
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Person'
                - $ref: '#/components/schemas/Organization'
      responses:
        '200':
          description: Successful response
  /document/{id}:
    get:
      summary: Get a document by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Person'
                  - $ref: '#/components/schemas/Organization'
  /documents/neighbors:
    post:
      summary: Get neighbors of documents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                docs:
                  type: array
                  items:
                    type: string
                n:
                  type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Document:
      type: object
      properties:
        _id:
          type: string
        dataset:
          type: string
        dtype:
          type: string
        sources:
          type: array
          items:
            type: string
        version:
          type: string
        date_updated:
          type: integer
        date_added:
          type: integer
    Target:
      allOf:
        - $ref: '#/components/schemas/Document'
        - type: object
          properties:
            actor:
              type: string
            target:
              type: string
            delay:
              type: integer
            recurring:
              type: boolean
            options:
              type: array
              items:
                type: string
    Person:
      allOf:
        - $ref: '#/components/schemas/Document'
        - type: object
          properties:
            fname:
              type: string
            mname:
              type: string
            lname:
              type: string
            bio:
              type: string
            dob:
              type: string
            race:
              type: string
            region:
              type: string
            misc:
              type: array
              items:
                type: string
            etype:
              type: string
            eid:
              type: string
    Organization:
      allOf:
        - $ref: '#/components/schemas/Document'
        - type: object
          properties:
            reg:
              type: string
            name:
              type: string
            bio:
              type: string
            country:
              type: string
            website:
              type: string
            etype:
              type: string
            eid:
              type: string
